theme: jekyll-theme-cayman
title: Rodolfo Lyu Shimotsu
email: rodolfoshimotsu@gmail.com
description: Engenheiro Elétrico | Desenvolvedor | Pesquisador
github_username: shimotsulyu
facebook_username: slyu89

