theme: jekyll-theme-cayman
title: Rodolfo Lyu Shimotsu
description: Engenheiro Elétrico | Desenvolvedor | Pesquisador
# Includes an icon in the footer for each user name you enter
footer-links:
  github: shimotsulyu
  faceboo: slyu89
  linkedin: rodolfo-lyu-shimotsu-127860179
